import type { Cell, CellGrid, RGB } from './types.js';
import { cellsToAnsi } from '../render/ansi.js';

// Browser-safe UTF-8 byte length — avoids Buffer so this file is usable in
// both Node CLI and the web bundle.
function utf8ByteLength(s: string): number {
  let n = 0;
  for (let i = 0; i < s.length; i++) {
    const code = s.charCodeAt(i);
    if (code < 0x80) n += 1;
    else if (code < 0x800) n += 2;
    else if ((code & 0xfc00) === 0xd800) {
      n += 4;
      i++;
    } else n += 3;
  }
  return n;
}

function luma(rgb: RGB): number {
  return (0.299 * rgb[0] + 0.587 * rgb[1] + 0.114 * rgb[2]) / 255;
}

// Quantize each channel to 4 bits (16 levels). nvim caps total highlight
// groups per session, and truecolor gifs create near-unique (fg,bg) pairs
// for every cell → E849. 4 bits/channel keeps unique pairs bounded and
// lets adjacent near-identical cells merge into a single run.
function quant(n: number): number {
  return Math.round(n / 17) * 17;
}

function toHex(rgb: RGB): string {
  const h = (n: number) => quant(n).toString(16).padStart(2, '0');
  return '#' + h(rgb[0]) + h(rgb[1]) + h(rgb[2]);
}

function skipBg(cell: Cell, threshold: number): boolean {
  if (threshold <= 0) return false;
  if (threshold >= 1) return true;
  return luma(cell.bg) < threshold;
}

function sameRunColor(a: Cell, b: Cell, threshold: number): boolean {
  const fgEq =
    quant(a.fg[0]) === quant(b.fg[0]) &&
    quant(a.fg[1]) === quant(b.fg[1]) &&
    quant(a.fg[2]) === quant(b.fg[2]);
  if (!fgEq) return false;
  const aSkip = skipBg(a, threshold);
  const bSkip = skipBg(b, threshold);
  if (aSkip !== bSkip) return false;
  if (aSkip) return true;
  return (
    quant(a.bg[0]) === quant(b.bg[0]) &&
    quant(a.bg[1]) === quant(b.bg[1]) &&
    quant(a.bg[2]) === quant(b.bg[2])
  );
}

interface ColorRun {
  sb: number;
  eb: number;
  fg: string;
  bg: string;
}

export function colorRuns(grid: CellGrid, backgroundThreshold: number): ColorRun[][] {
  return grid.map((row) => {
    const runs: ColorRun[] = [];
    if (row.length === 0) return runs;
    let sb = 0;
    let b = 0;
    let cur: Cell = row[0]!;
    for (let x = 0; x < row.length; x++) {
      const cell = row[x]!;
      const glyphBytes = utf8ByteLength(cell.glyph);
      if (x > 0 && !sameRunColor(cur, cell, backgroundThreshold)) {
        runs.push({
          sb,
          eb: b,
          fg: toHex(cur.fg),
          bg: skipBg(cur, backgroundThreshold) ? 'NONE' : toHex(cur.bg),
        });
        sb = b;
        cur = cell;
      }
      b += glyphBytes;
    }
    runs.push({
      sb,
      eb: b,
      fg: toHex(cur.fg),
      bg: skipBg(cur, backgroundThreshold) ? 'NONE' : toHex(cur.bg),
    });
    return runs;
  });
}

function escLua(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

export function emitGoData(
  grids: CellGrid[],
  delays: number[],
  cols: number,
  rows: number,
  pkg: string,
  backgroundThreshold: number,
): string {
  const ansiFrames = grids.map((g) =>
    cellsToAnsi(g, { color: true, background: true, bgThreshold: backgroundThreshold }),
  );
  const lines: string[] = [
    '// Code generated by milli export; DO NOT EDIT.',
    `package ${pkg}`,
    '',
    `const Cols = ${cols}`,
    `const Rows = ${rows}`,
    '',
    `var Delays = []int{${delays.join(', ')}}`,
    '',
    'var Frames = []string{',
  ];
  for (const f of ansiFrames) lines.push('\t' + JSON.stringify(f) + ',');
  lines.push('}', '');
  return lines.join('\n');
}

export function emitGoHelper(pkg: string): string {
  return `// Code generated by milli export; edit freely or delete if you prefer your own driver.
package ${pkg}

import (
\t"strings"
\t"time"

\ttea "github.com/charmbracelet/bubbletea"
)

// TickMsg advances the splash to Index.
type TickMsg struct{ Index int }

// DoneMsg signals splash playback is complete.
type DoneMsg struct{}

// Tick schedules the next frame advance based on Delays[current].
// Emits TickMsg{next} or DoneMsg when frames are exhausted.
func Tick(current int) tea.Cmd {
\tif current < 0 || current >= len(Delays) {
\t\treturn func() tea.Msg { return DoneMsg{} }
\t}
\td := time.Duration(Delays[current]) * time.Millisecond
\treturn tea.Tick(d, func(time.Time) tea.Msg {
\t\tnext := current + 1
\t\tif next >= len(Frames) {
\t\t\treturn DoneMsg{}
\t\t}
\t\treturn TickMsg{Index: next}
\t})
}

// Render returns frame idx centered inside a (width × height) area.
// If the area is smaller than the frame, content is emitted unpadded.
func Render(idx, width, height int) string {
\tif idx < 0 {
\t\tidx = 0
\t}
\tif idx >= len(Frames) {
\t\tidx = len(Frames) - 1
\t}
\tframe := Frames[idx]

\tpadLeft := 0
\tif width > Cols {
\t\tpadLeft = (width - Cols) / 2
\t}
\tpadTop := 0
\tif height > Rows {
\t\tpadTop = (height - Rows) / 2
\t}

\tlines := strings.Split(frame, "\\n")
\tif len(lines) > 0 && lines[len(lines)-1] == "" {
\t\tlines = lines[:len(lines)-1]
\t}
\tpadStr := strings.Repeat(" ", padLeft)

\tvar b strings.Builder
\tb.Grow(len(frame) + padLeft*len(lines) + padTop)
\tfor i := 0; i < padTop; i++ {
\t\tb.WriteByte('\\n')
\t}
\tfor i, line := range lines {
\t\tb.WriteString(padStr)
\t\tb.WriteString(line)
\t\tif i < len(lines)-1 {
\t\t\tb.WriteByte('\\n')
\t\t}
\t}
\treturn b.String()
}
`;
}

export function emitLuaData(
  grids: CellGrid[],
  delays: number[],
  cols: number,
  rows: number,
  color: boolean,
  backgroundThreshold: number,
): string {
  // Lua has a 65536-constants-per-function cap, so wrap each frame's table
  // literal in its own anonymous function to give each a fresh constant pool.
  const plain = grids.map((g) => g.map((row) => row.map((c) => c.glyph).join('')));
  const lines: string[] = [
    '-- Code generated by milli export; DO NOT EDIT.',
    `local M = { cols = ${cols}, rows = ${rows}, delays = { ${delays.join(', ')} } }`,
    '',
    'M.frames = {}',
  ];
  for (let i = 0; i < plain.length; i++) {
    lines.push(`M.frames[${i + 1}] = (function() return {`);
    for (const line of plain[i]!) lines.push(`  "${escLua(line)}",`);
    lines.push('} end)()');
  }
  lines.push('');

  if (color) {
    const colors = grids.map((g) => colorRuns(g, backgroundThreshold));
    lines.push('M.colors = {}');
    for (let i = 0; i < colors.length; i++) {
      lines.push(`M.colors[${i + 1}] = (function() return {`);
      for (const row of colors[i]!) {
        const parts = row.map((r) => `{${r.sb},${r.eb},"${r.fg}","${r.bg}"}`);
        lines.push(`  { ${parts.join(', ')} },`);
      }
      lines.push('} end)()');
    }
    lines.push('');
  }

  lines.push('return M', '');
  return lines.join('\n');
}

export function emitJson(
  grids: CellGrid[],
  delays: number[],
  cols: number,
  rows: number,
): string {
  const frames = grids.map((grid) => ({
    cells: grid.map((row) =>
      row.map((c) => ({
        g: c.glyph,
        fg: [c.fg[0], c.fg[1], c.fg[2]],
        bg: [c.bg[0], c.bg[1], c.bg[2]],
      })),
    ),
  }));
  return JSON.stringify({ version: 1, cols, rows, delays, frames });
}
